"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import {AnimatePresence} from "framer-motion";
import PageTrans from '.././components/page_transistion'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <AnimatePresence mode="wait">
      {/* <PageTrans> */}
      {children}
      {/* </PageTrans> */}
        
      </AnimatePresence>
      </body>
    </html>
  );
}
